version: '3.8'

networks:
  s3bucket:
    name: s3bucket

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Go version 1, 1.18, 1.17
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "1.19-bullseye"
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env

    volumes:
      - ..:/workspace/s3bucket:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - s3bucket

  localstack:
    image: localstack/localstack
    hostname: ${LOCALSTACK_HOSTNAME}
    environment:
      EAGER_SERVICE_LOADING: 1
      PERSISTENCE: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      START_WEB: 1
      # Custom scripts dependencies
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      S3_BUCKET: "${S3_BUCKET}"
      LOCALSTACK_HOST: ${LOCALSTACK_HOSTNAME}
    networks:
      - s3bucket
    volumes:
      - ./setup/localstack.sh:/etc/localstack/init/ready.d/localstack.sh
      - /var/run/docker.sock:/var/run/docker.sock
