version: '3.8'

networks:
  s3bucket:
    name: s3bucket

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Go version 1, 1.18, 1.17
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "1.19-bullseye"
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env

    volumes:
      - ..:/workspace/s3bucket:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - s3bucket